//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteAllAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admintable
    {
        public int id { get; set; }
        public string adminname { get; set; }
        public string adminpassword { get; set; }
        public Nullable<int> roleid { get; set; }
        public string RoleName { get; set; }
    
        public virtual tblrole tblrole { get; set; }
    }
}
