//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteAllAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blog
    {
        public int id { get; set; }
        public Nullable<int> cid { get; set; }
        public string blogtitle { get; set; }
        public string blogDesc { get; set; }
        public string blogimage { get; set; }
        public Nullable<System.DateTime> blogentrydate { get; set; }
        public string fldextra { get; set; }
        public string fldextra1 { get; set; }
        public string fldextra2 { get; set; }
        public string fldextra3 { get; set; }
        public string fldextra4 { get; set; }
    
        public virtual tblcategory tblcategory { get; set; }
    }
}
