//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteAllAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HomeSlider
    {
        public int id { get; set; }
        public string homePhoto { get; set; }
        public string homestatement { get; set; }
        public Nullable<bool> fldstatus { get; set; }
        public Nullable<System.DateTime> flddoe { get; set; }
        public string slidesc { get; set; }
    }
}
