//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteAllAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jobSubcategory
    {
        public int JobSubCategoryId { get; set; }
        public Nullable<int> JobCatId { get; set; }
        public string JobSubcategoryname { get; set; }
        public string desscription { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<bool> IsShow { get; set; }
        public Nullable<bool> Flstatus { get; set; }
        public string fldextra { get; set; }
        public string fldextra1 { get; set; }
        public string fldextra2 { get; set; }
        public string fldextra3 { get; set; }
        public string fldextra4 { get; set; }
        public string fldextra5 { get; set; }
    
        public virtual tblcategory tblcategory { get; set; }
    }
}
