//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteAllAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteSetting
    {
        public int id { get; set; }
        public string sitephoneno { get; set; }
        public string siteemailid { get; set; }
        public string sitecontactno2 { get; set; }
        public string siteAddress { get; set; }
        public string sitelogo { get; set; }
        public string fblink { get; set; }
        public string twiterlink { get; set; }
        public string gpluslink { get; set; }
        public string shortaddress { get; set; }
        public string sitename { get; set; }
        public string shortdescription { get; set; }
    }
}
