//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteAllAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblcategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblcategory()
        {
            this.Blogs = new HashSet<Blog>();
            this.jobSubcategories = new HashSet<jobSubcategory>();
            this.tbljoblists = new HashSet<tbljoblist>();
        }
    
        public int fldcatid { get; set; }
        public string fldcategoryname { get; set; }
        public string fldcategorytitle { get; set; }
        public string fldcategorykeyword { get; set; }
        public string flddescription { get; set; }
        public Nullable<bool> IsShow { get; set; }
        public string fldextra { get; set; }
        public string fldextra1 { get; set; }
        public string fldextra2 { get; set; }
        public string fldextra3 { get; set; }
        public Nullable<bool> fldstatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Blog> Blogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<jobSubcategory> jobSubcategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbljoblist> tbljoblists { get; set; }
    }
}
