//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteAllAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblenquiry
    {
        public int fldenquiryid { get; set; }
        public Nullable<int> fldjoblistid { get; set; }
        public string fldname { get; set; }
        public string fldemail { get; set; }
        public string fldfulladdress { get; set; }
        public string fldmobno { get; set; }
        public string fldextra { get; set; }
        public string fldextra1 { get; set; }
        public string fldextra2 { get; set; }
        public string fldextra3 { get; set; }
        public Nullable<bool> fldstatus { get; set; }
    
        public virtual tbljoblist tbljoblist { get; set; }
    }
}
