//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteAllAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbljoblist
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbljoblist()
        {
            this.tblenquiries = new HashSet<tblenquiry>();
            this.tbljobimages = new HashSet<tbljobimage>();
        }
    
        public int fldjoblistid { get; set; }
        public Nullable<int> fldjobcategoryid { get; set; }
        public Nullable<int> fldsubcatid { get; set; }
        public Nullable<int> fldstateid { get; set; }
        public Nullable<int> fldcityid { get; set; }
        public string fldjobtitle { get; set; }
        public string fldjobname { get; set; }
        public string fldjobdescription { get; set; }
        public string fldexperience { get; set; }
        public string fldage { get; set; }
        public string fldeducation { get; set; }
        public string fldextra { get; set; }
        public string fldextra1 { get; set; }
        public string fldextra2 { get; set; }
        public string fldextra3 { get; set; }
        public Nullable<bool> fldstatus { get; set; }
    
        public virtual tblcategory tblcategory { get; set; }
        public virtual tblcity tblcity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblenquiry> tblenquiries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbljobimage> tbljobimages { get; set; }
        public virtual tblstate tblstate { get; set; }
    }
}
