//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteAllAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLiveEnquiry
    {
        public int id { get; set; }
        public string CustomerName { get; set; }
        public string Customer_Email { get; set; }
        public string Customer_phone { get; set; }
        public string customer_monthly_Income { get; set; }
        public string invest_amount { get; set; }
        public string CurentCity { get; set; }
        public string stateresidance { get; set; }
        public string ApplyFor { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string fldextra { get; set; }
        public string fldextra2 { get; set; }
        public string fldextra1 { get; set; }
    }
}
