//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteAllAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblproduct
    {
        public int id { get; set; }
        public string fldprodtitle { get; set; }
        public string fldprodsubtitle { get; set; }
        public string flddescription { get; set; }
        public Nullable<System.DateTime> entrydate { get; set; }
        public string fldseotitle { get; set; }
        public string fldseokeyword { get; set; }
        public string fldextra { get; set; }
        public string fldextra1 { get; set; }
        public string productimage { get; set; }
    }
}
