//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteAllAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblregistration
    {
        public int fldregistrationid { get; set; }
        public string fldemployeetype { get; set; }
        public Nullable<int> fldroleid { get; set; }
        public string fldname { get; set; }
        public string fldemail { get; set; }
        public string fldmobno { get; set; }
        public string fldaddress { get; set; }
        public string fldextra { get; set; }
        public string fldextra1 { get; set; }
        public string fldextra2 { get; set; }
        public Nullable<bool> fldstatus { get; set; }
    
        public virtual tblrole tblrole { get; set; }
    }
}
