//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteAllAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblstate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblstate()
        {
            this.tblcities = new HashSet<tblcity>();
            this.tbljoblists = new HashSet<tbljoblist>();
        }
    
        public int fldstateid { get; set; }
        public string fldstatename { get; set; }
        public string fldextra { get; set; }
        public string fldextra1 { get; set; }
        public string fldextra2 { get; set; }
        public Nullable<bool> fldstatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblcity> tblcities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbljoblist> tbljoblists { get; set; }
        public virtual tblstate tblstate1 { get; set; }
        public virtual tblstate tblstate2 { get; set; }
    }
}
