//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteAllAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserDetail()
        {
            this.Addextrafeatures = new HashSet<Addextrafeature>();
            this.tblnotifications = new HashSet<tblnotification>();
            this.tblPayments = new HashSet<tblPayment>();
        }
    
        public int id { get; set; }
        public string fldName { get; set; }
        public string fldMobile { get; set; }
        public string fldemail { get; set; }
        public string fldsreet { get; set; }
        public string fldstate { get; set; }
        public string fldcity { get; set; }
        public string fldpincode { get; set; }
        public string fldstorename { get; set; }
        public string fldstoreemail { get; set; }
        public string fldstorecontactno { get; set; }
        public string fldshopcode { get; set; }
        public string fldstoreaddress { get; set; }
        public string fldstorestate { get; set; }
        public string fldstorecity { get; set; }
        public string fldstorepincode { get; set; }
        public string fldpassword { get; set; }
        public Nullable<bool> fldstatus { get; set; }
        public Nullable<System.DateTime> fldcreateddate { get; set; }
        public string fldimage { get; set; }
        public Nullable<int> roletype { get; set; }
        public string StatusKey { get; set; }
        public string StatusDescription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Addextrafeature> Addextrafeatures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblnotification> tblnotifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPayment> tblPayments { get; set; }
        public virtual tblrole tblrole { get; set; }
    }
}
