//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteAllAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebGallery
    {
        public int gid { get; set; }
        public string Gimage { get; set; }
        public string gimagedecription { get; set; }
        public Nullable<bool> fldstatus { get; set; }
        public Nullable<System.DateTime> GDate { get; set; }
        public string fldextra { get; set; }
        public string fldextra1 { get; set; }
        public string fldextra2 { get; set; }
    }
}
